root = "."
tmp_dir = "/tmp"

[build]
  bin = ""
  cmd = "yarn build"
  delay = 1000
  exclude_dir = ["build", "tmp", "node_modules"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "date"
  include_dir = []
  include_ext = ["tpl", "tmpl", "html", 'jsx', 'js']
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
