### Nginx HTTP origin configuration for %(nginx_server_name)s

server {
        listen 80;
        server_name %(nginx_server_name)s www.%(nginx_server_name)s;

        access_log /var/log/nginx/%(nginx_server_name)s_access.log friendfeed;

        root %(www_public_path)s;

        location /a/events {
                 proxy_pass_header Server;
                 proxy_redirect off;
                 proxy_http_version 1.1;
                 proxy_set_header Connection "";
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header X-Forwarded-Proto https;
                 proxy_set_header X-Scheme https;
                 proxy_set_header X-Forwarded-Protocol ssl;

                 proxy_buffering off;
                 proxy_cache off;
                 proxy_read_timeout 1h;
                 proxy_send_timeout 1h;
                 proxy_pass http://%(ffweb_bind)s;
        }

        location / {
                 proxy_pass_header Server;
                 proxy_redirect off;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header X-Forwarded-Proto https;
                 proxy_set_header X-Scheme https;
                 proxy_set_header X-Forwarded-Protocol ssl;

                 client_max_body_size %(nginx_client_max_body_size)iM;
                 proxy_pass http://%(ffweb_bind)s;
        }

        error_page 500 502 503 504 /usr/share/nginx/html/50x.html;
}
