// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArchiveSummary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	DateStart            int32    `protobuf:"varint,3,opt,name=date_start,json=dateStart,proto3" json:"date_start,omitempty"`
	DateEnd              int32    `protobuf:"varint,4,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	ElapsedTime          int32    `protobuf:"varint,5,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveSummary) Reset()         { *m = ArchiveSummary{} }
func (m *ArchiveSummary) String() string { return proto.CompactTextString(m) }
func (*ArchiveSummary) ProtoMessage()    {}
func (*ArchiveSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{0}
}

func (m *ArchiveSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveSummary.Unmarshal(m, b)
}
func (m *ArchiveSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveSummary.Marshal(b, m, deterministic)
}
func (m *ArchiveSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveSummary.Merge(m, src)
}
func (m *ArchiveSummary) XXX_Size() int {
	return xxx_messageInfo_ArchiveSummary.Size(m)
}
func (m *ArchiveSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveSummary proto.InternalMessageInfo

func (m *ArchiveSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ArchiveSummary) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ArchiveSummary) GetDateStart() int32 {
	if m != nil {
		return m.DateStart
	}
	return 0
}

func (m *ArchiveSummary) GetDateEnd() int32 {
	if m != nil {
		return m.DateEnd
	}
	return 0
}

func (m *ArchiveSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

type StockInfo struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullName string `protobuf:"bytes,20,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Market   string `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	// float preClose = 3;        // 前收价
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ListDate             int32    `protobuf:"varint,6,opt,name=listDate,proto3" json:"listDate,omitempty"`
	LastTradeDate        int32    `protobuf:"varint,7,opt,name=lastTradeDate,proto3" json:"lastTradeDate,omitempty"`
	DelistDate           int32    `protobuf:"varint,8,opt,name=delistDate,proto3" json:"delistDate,omitempty"`
	CircuShare           int64    `protobuf:"varint,9,opt,name=circuShare,proto3" json:"circuShare,omitempty"`
	TotalShare           int64    `protobuf:"varint,10,opt,name=totalShare,proto3" json:"totalShare,omitempty"`
	Industry             string   `protobuf:"bytes,11,opt,name=industry,proto3" json:"industry,omitempty"`
	Block                string   `protobuf:"bytes,12,opt,name=block,proto3" json:"block,omitempty"`
	Concepts             []string `protobuf:"bytes,13,rep,name=concepts,proto3" json:"concepts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockInfo) Reset()         { *m = StockInfo{} }
func (m *StockInfo) String() string { return proto.CompactTextString(m) }
func (*StockInfo) ProtoMessage()    {}
func (*StockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{1}
}

func (m *StockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockInfo.Unmarshal(m, b)
}
func (m *StockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockInfo.Marshal(b, m, deterministic)
}
func (m *StockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockInfo.Merge(m, src)
}
func (m *StockInfo) XXX_Size() int {
	return xxx_messageInfo_StockInfo.Size(m)
}
func (m *StockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StockInfo proto.InternalMessageInfo

func (m *StockInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StockInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StockInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *StockInfo) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *StockInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StockInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StockInfo) GetListDate() int32 {
	if m != nil {
		return m.ListDate
	}
	return 0
}

func (m *StockInfo) GetLastTradeDate() int32 {
	if m != nil {
		return m.LastTradeDate
	}
	return 0
}

func (m *StockInfo) GetDelistDate() int32 {
	if m != nil {
		return m.DelistDate
	}
	return 0
}

func (m *StockInfo) GetCircuShare() int64 {
	if m != nil {
		return m.CircuShare
	}
	return 0
}

func (m *StockInfo) GetTotalShare() int64 {
	if m != nil {
		return m.TotalShare
	}
	return 0
}

func (m *StockInfo) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *StockInfo) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *StockInfo) GetConcepts() []string {
	if m != nil {
		return m.Concepts
	}
	return nil
}

// Form 10-K 年报?
type StockF10 struct {
	EPS                  int32    `protobuf:"varint,1,opt,name=EPS,proto3" json:"EPS,omitempty"`
	TotalAssets          int64    `protobuf:"varint,2,opt,name=totalAssets,proto3" json:"totalAssets,omitempty"`
	FlowProperty         int64    `protobuf:"varint,3,opt,name=flowProperty,proto3" json:"flowProperty,omitempty"`
	NetWorth             int32    `protobuf:"varint,4,opt,name=netWorth,proto3" json:"netWorth,omitempty"`
	MainIncoming         int64    `protobuf:"varint,5,opt,name=mainIncoming,proto3" json:"mainIncoming,omitempty"`
	MainProfit           int64    `protobuf:"varint,6,opt,name=mainProfit,proto3" json:"mainProfit,omitempty"`
	TotalProfit          int64    `protobuf:"varint,7,opt,name=totalProfit,proto3" json:"totalProfit,omitempty"`
	NetProfit            int64    `protobuf:"varint,8,opt,name=netProfit,proto3" json:"netProfit,omitempty"`
	ShareHolders         int32    `protobuf:"varint,9,opt,name=shareHolders,proto3" json:"shareHolders,omitempty"`
	ReportDate           int32    `protobuf:"varint,10,opt,name=reportDate,proto3" json:"reportDate,omitempty"`
	LiquidRatio          int32    `protobuf:"varint,11,opt,name=liquidRatio,proto3" json:"liquidRatio,omitempty"`
	QuickRatio           int32    `protobuf:"varint,12,opt,name=quickRatio,proto3" json:"quickRatio,omitempty"`
	UDPPS                int32    `protobuf:"varint,13,opt,name=UDPPS,proto3" json:"UDPPS,omitempty"`
	CurrentLiabilities   int64    `protobuf:"varint,14,opt,name=currentLiabilities,proto3" json:"currentLiabilities,omitempty"`
	TotalLiabilities     int64    `protobuf:"varint,15,opt,name=totalLiabilities,proto3" json:"totalLiabilities,omitempty"`
	TotalHolderEquity    int64    `protobuf:"varint,16,opt,name=totalHolderEquity,proto3" json:"totalHolderEquity,omitempty"`
	CapitalReserve       int64    `protobuf:"varint,17,opt,name=capitalReserve,proto3" json:"capitalReserve,omitempty"`
	InvestmentIncome     int64    `protobuf:"varint,18,opt,name=investmentIncome,proto3" json:"investmentIncome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockF10) Reset()         { *m = StockF10{} }
func (m *StockF10) String() string { return proto.CompactTextString(m) }
func (*StockF10) ProtoMessage()    {}
func (*StockF10) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{2}
}

func (m *StockF10) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockF10.Unmarshal(m, b)
}
func (m *StockF10) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockF10.Marshal(b, m, deterministic)
}
func (m *StockF10) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockF10.Merge(m, src)
}
func (m *StockF10) XXX_Size() int {
	return xxx_messageInfo_StockF10.Size(m)
}
func (m *StockF10) XXX_DiscardUnknown() {
	xxx_messageInfo_StockF10.DiscardUnknown(m)
}

var xxx_messageInfo_StockF10 proto.InternalMessageInfo

func (m *StockF10) GetEPS() int32 {
	if m != nil {
		return m.EPS
	}
	return 0
}

func (m *StockF10) GetTotalAssets() int64 {
	if m != nil {
		return m.TotalAssets
	}
	return 0
}

func (m *StockF10) GetFlowProperty() int64 {
	if m != nil {
		return m.FlowProperty
	}
	return 0
}

func (m *StockF10) GetNetWorth() int32 {
	if m != nil {
		return m.NetWorth
	}
	return 0
}

func (m *StockF10) GetMainIncoming() int64 {
	if m != nil {
		return m.MainIncoming
	}
	return 0
}

func (m *StockF10) GetMainProfit() int64 {
	if m != nil {
		return m.MainProfit
	}
	return 0
}

func (m *StockF10) GetTotalProfit() int64 {
	if m != nil {
		return m.TotalProfit
	}
	return 0
}

func (m *StockF10) GetNetProfit() int64 {
	if m != nil {
		return m.NetProfit
	}
	return 0
}

func (m *StockF10) GetShareHolders() int32 {
	if m != nil {
		return m.ShareHolders
	}
	return 0
}

func (m *StockF10) GetReportDate() int32 {
	if m != nil {
		return m.ReportDate
	}
	return 0
}

func (m *StockF10) GetLiquidRatio() int32 {
	if m != nil {
		return m.LiquidRatio
	}
	return 0
}

func (m *StockF10) GetQuickRatio() int32 {
	if m != nil {
		return m.QuickRatio
	}
	return 0
}

func (m *StockF10) GetUDPPS() int32 {
	if m != nil {
		return m.UDPPS
	}
	return 0
}

func (m *StockF10) GetCurrentLiabilities() int64 {
	if m != nil {
		return m.CurrentLiabilities
	}
	return 0
}

func (m *StockF10) GetTotalLiabilities() int64 {
	if m != nil {
		return m.TotalLiabilities
	}
	return 0
}

func (m *StockF10) GetTotalHolderEquity() int64 {
	if m != nil {
		return m.TotalHolderEquity
	}
	return 0
}

func (m *StockF10) GetCapitalReserve() int64 {
	if m != nil {
		return m.CapitalReserve
	}
	return 0
}

func (m *StockF10) GetInvestmentIncome() int64 {
	if m != nil {
		return m.InvestmentIncome
	}
	return 0
}

type IndexInfo struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StockInfos           []*StockInfo `protobuf:"bytes,3,rep,name=stockInfos,proto3" json:"stockInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexInfo) Reset()         { *m = IndexInfo{} }
func (m *IndexInfo) String() string { return proto.CompactTextString(m) }
func (*IndexInfo) ProtoMessage()    {}
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{3}
}

func (m *IndexInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexInfo.Unmarshal(m, b)
}
func (m *IndexInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexInfo.Marshal(b, m, deterministic)
}
func (m *IndexInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexInfo.Merge(m, src)
}
func (m *IndexInfo) XXX_Size() int {
	return xxx_messageInfo_IndexInfo.Size(m)
}
func (m *IndexInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IndexInfo proto.InternalMessageInfo

func (m *IndexInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexInfo) GetStockInfos() []*StockInfo {
	if m != nil {
		return m.StockInfos
	}
	return nil
}

type ETFInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETFInfo) Reset()         { *m = ETFInfo{} }
func (m *ETFInfo) String() string { return proto.CompactTextString(m) }
func (*ETFInfo) ProtoMessage()    {}
func (*ETFInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{4}
}

func (m *ETFInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETFInfo.Unmarshal(m, b)
}
func (m *ETFInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETFInfo.Marshal(b, m, deterministic)
}
func (m *ETFInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETFInfo.Merge(m, src)
}
func (m *ETFInfo) XXX_Size() int {
	return xxx_messageInfo_ETFInfo.Size(m)
}
func (m *ETFInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ETFInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ETFInfo proto.InternalMessageInfo

func (m *ETFInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ETFInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// K线
type KLine struct {
	Date                 int32    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Open                 float32  `protobuf:"fixed32,2,opt,name=open,proto3" json:"open,omitempty"`
	High                 float32  `protobuf:"fixed32,3,opt,name=high,proto3" json:"high,omitempty"`
	Low                  float32  `protobuf:"fixed32,4,opt,name=low,proto3" json:"low,omitempty"`
	Close                float32  `protobuf:"fixed32,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume               int64    `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount               float32  `protobuf:"fixed32,7,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KLine) Reset()         { *m = KLine{} }
func (m *KLine) String() string { return proto.CompactTextString(m) }
func (*KLine) ProtoMessage()    {}
func (*KLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{5}
}

func (m *KLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KLine.Unmarshal(m, b)
}
func (m *KLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KLine.Marshal(b, m, deterministic)
}
func (m *KLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KLine.Merge(m, src)
}
func (m *KLine) XXX_Size() int {
	return xxx_messageInfo_KLine.Size(m)
}
func (m *KLine) XXX_DiscardUnknown() {
	xxx_messageInfo_KLine.DiscardUnknown(m)
}

var xxx_messageInfo_KLine proto.InternalMessageInfo

func (m *KLine) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *KLine) GetOpen() float32 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *KLine) GetHigh() float32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *KLine) GetLow() float32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *KLine) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *KLine) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *KLine) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type KLineRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	KLine                *KLine   `protobuf:"bytes,3,opt,name=kLine,proto3" json:"kLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KLineRequest) Reset()         { *m = KLineRequest{} }
func (m *KLineRequest) String() string { return proto.CompactTextString(m) }
func (*KLineRequest) ProtoMessage()    {}
func (*KLineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{6}
}

func (m *KLineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KLineRequest.Unmarshal(m, b)
}
func (m *KLineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KLineRequest.Marshal(b, m, deterministic)
}
func (m *KLineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KLineRequest.Merge(m, src)
}
func (m *KLineRequest) XXX_Size() int {
	return xxx_messageInfo_KLineRequest.Size(m)
}
func (m *KLineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KLineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KLineRequest proto.InternalMessageInfo

func (m *KLineRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *KLineRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *KLineRequest) GetKLine() *KLine {
	if m != nil {
		return m.KLine
	}
	return nil
}

// 分红
type Dividend struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Date                 int32    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Cash                 float32  `protobuf:"fixed32,4,opt,name=cash,proto3" json:"cash,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Count                float32  `protobuf:"fixed32,6,opt,name=count,proto3" json:"count,omitempty"`
	Rate                 float32  `protobuf:"fixed32,7,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dividend) Reset()         { *m = Dividend{} }
func (m *Dividend) String() string { return proto.CompactTextString(m) }
func (*Dividend) ProtoMessage()    {}
func (*Dividend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{7}
}

func (m *Dividend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dividend.Unmarshal(m, b)
}
func (m *Dividend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dividend.Marshal(b, m, deterministic)
}
func (m *Dividend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dividend.Merge(m, src)
}
func (m *Dividend) XXX_Size() int {
	return xxx_messageInfo_Dividend.Size(m)
}
func (m *Dividend) XXX_DiscardUnknown() {
	xxx_messageInfo_Dividend.DiscardUnknown(m)
}

var xxx_messageInfo_Dividend proto.InternalMessageInfo

func (m *Dividend) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Dividend) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Dividend) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Dividend) GetCash() float32 {
	if m != nil {
		return m.Cash
	}
	return 0
}

func (m *Dividend) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Dividend) GetCount() float32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Dividend) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterType((*ArchiveSummary)(nil), "proto.ArchiveSummary")
	proto.RegisterType((*StockInfo)(nil), "proto.StockInfo")
	proto.RegisterType((*StockF10)(nil), "proto.StockF10")
	proto.RegisterType((*IndexInfo)(nil), "proto.IndexInfo")
	proto.RegisterType((*ETFInfo)(nil), "proto.ETFInfo")
	proto.RegisterType((*KLine)(nil), "proto.KLine")
	proto.RegisterType((*KLineRequest)(nil), "proto.KLineRequest")
	proto.RegisterType((*Dividend)(nil), "proto.Dividend")
}

func init() { proto.RegisterFile("stock.proto", fileDescriptor_c87a7814fbd674bd) }

var fileDescriptor_c87a7814fbd674bd = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdf, 0x6f, 0x23, 0x35,
	0x10, 0x56, 0x76, 0x9b, 0x26, 0x3b, 0x49, 0x4b, 0xcf, 0x3a, 0xa1, 0x05, 0x01, 0x0a, 0x2b, 0x84,
	0x2a, 0x04, 0xd5, 0x71, 0xfc, 0x05, 0x27, 0xb5, 0x27, 0x2a, 0x4e, 0x28, 0x72, 0x8a, 0x78, 0x3c,
	0x39, 0xbb, 0xd3, 0x8b, 0x95, 0x5d, 0x3b, 0xb5, 0xbd, 0x39, 0xf2, 0x77, 0xf0, 0xc8, 0x1b, 0x7f,
	0x27, 0x12, 0x68, 0xc6, 0x9b, 0x5f, 0x57, 0x1e, 0x7a, 0x4f, 0x99, 0xef, 0xfb, 0xc6, 0xde, 0xcf,
	0x33, 0xf6, 0x04, 0x46, 0x3e, 0xd8, 0x72, 0x79, 0xb5, 0x72, 0x36, 0x58, 0xd1, 0xe7, 0x9f, 0xe2,
	0xcf, 0x1e, 0x9c, 0xbf, 0x72, 0xe5, 0x42, 0xaf, 0x71, 0xd6, 0x36, 0x8d, 0x72, 0x1b, 0x71, 0x0e,
	0x89, 0xae, 0xf2, 0xde, 0xa4, 0x77, 0x99, 0xc9, 0x44, 0x57, 0xe2, 0x39, 0xf4, 0x4b, 0xdb, 0x9a,
	0x90, 0x27, 0x93, 0xde, 0x65, 0x5f, 0x46, 0x20, 0xbe, 0x04, 0xa8, 0x54, 0xc0, 0xb7, 0x3e, 0x28,
	0x17, 0xf2, 0x94, 0xa5, 0x8c, 0x98, 0x19, 0x11, 0xe2, 0x33, 0x18, 0xb2, 0x8c, 0xa6, 0xca, 0x4f,
	0x58, 0x1c, 0x10, 0xbe, 0x31, 0x95, 0xf8, 0x1a, 0xc6, 0x58, 0xab, 0x95, 0xc7, 0xea, 0x6d, 0xd0,
	0x0d, 0xe6, 0x7d, 0x96, 0x47, 0x1d, 0x77, 0xa7, 0x1b, 0x2c, 0xfe, 0x4d, 0x20, 0x9b, 0x91, 0xd9,
	0x5b, 0x73, 0x6f, 0x1f, 0x19, 0x12, 0x70, 0x62, 0x54, 0x83, 0xec, 0x27, 0x93, 0x1c, 0x8b, 0xcf,
	0x61, 0x78, 0xdf, 0xd6, 0xf5, 0xaf, 0xc4, 0x3f, 0x67, 0x7e, 0x87, 0xc5, 0xa7, 0x70, 0xda, 0x28,
	0xb7, 0xc4, 0x68, 0x33, 0x93, 0x1d, 0xa2, 0x7d, 0xc2, 0x66, 0x85, 0xec, 0x2f, 0x93, 0x1c, 0x53,
	0xae, 0x0f, 0x2a, 0xb4, 0x9e, 0x6d, 0x65, 0xb2, 0x43, 0xb4, 0x7f, 0xad, 0x7d, 0xb8, 0x56, 0x01,
	0xf3, 0x53, 0x36, 0xbc, 0xc3, 0xe2, 0x1b, 0x38, 0xab, 0x95, 0x0f, 0x77, 0x4e, 0x55, 0xc8, 0x09,
	0x03, 0x4e, 0x38, 0x26, 0xc5, 0x57, 0x00, 0x15, 0xee, 0xf6, 0x18, 0x72, 0xca, 0x01, 0x43, 0x7a,
	0xa9, 0x5d, 0xd9, 0xce, 0x16, 0xca, 0x61, 0x9e, 0x4d, 0x7a, 0x97, 0xa9, 0x3c, 0x60, 0x48, 0x0f,
	0x36, 0xa8, 0x3a, 0xea, 0x10, 0xf5, 0x3d, 0x43, 0x0e, 0xb5, 0xa9, 0x5a, 0x1f, 0xdc, 0x26, 0x1f,
	0xc5, 0x0a, 0x6c, 0x31, 0xb5, 0x70, 0x5e, 0xdb, 0x72, 0x99, 0x8f, 0x59, 0x88, 0x80, 0x56, 0x94,
	0xd6, 0x94, 0xb8, 0x0a, 0x3e, 0x3f, 0x9b, 0xa4, 0xb4, 0x62, 0x8b, 0x8b, 0x7f, 0x4e, 0x60, 0xc8,
	0x1d, 0x78, 0xfd, 0xe3, 0x0b, 0x71, 0x01, 0xe9, 0xcd, 0x74, 0xc6, 0x1d, 0xe8, 0x4b, 0x0a, 0xc5,
	0x04, 0x46, 0xfc, 0xe9, 0x57, 0xde, 0x63, 0xf0, 0xdc, 0x89, 0x54, 0x1e, 0x52, 0xa2, 0x80, 0xf1,
	0x7d, 0x6d, 0xdf, 0x4f, 0x9d, 0x5d, 0xa1, 0x0b, 0x1b, 0x2e, 0x7d, 0x2a, 0x8f, 0x38, 0x32, 0x60,
	0x30, 0xfc, 0x6e, 0x5d, 0x58, 0x74, 0x97, 0x64, 0x87, 0x69, 0x7d, 0xa3, 0xb4, 0xb9, 0x35, 0xa5,
	0x6d, 0xb4, 0x79, 0xc7, 0xed, 0x48, 0xe5, 0x11, 0x47, 0x25, 0x21, 0x3c, 0x75, 0xf6, 0x5e, 0x07,
	0x6e, 0x4b, 0x2a, 0x0f, 0x98, 0x9d, 0xcb, 0x2e, 0x61, 0x70, 0xe0, 0xb2, 0xcb, 0xf8, 0x02, 0x32,
	0x83, 0xa1, 0xd3, 0x87, 0xac, 0xef, 0x09, 0xf2, 0xe0, 0xa9, 0xb6, 0x3f, 0xdb, 0xba, 0x42, 0xe7,
	0xb9, 0x29, 0x7d, 0x79, 0xc4, 0x91, 0x07, 0x87, 0x2b, 0xeb, 0x62, 0x5b, 0x21, 0xb6, 0x75, 0xcf,
	0x90, 0x87, 0x5a, 0x3f, 0xb4, 0xba, 0x92, 0x2a, 0x68, 0xcb, 0x9d, 0xe9, 0xcb, 0x43, 0x8a, 0x76,
	0x78, 0x68, 0x75, 0xb9, 0x8c, 0x09, 0xe3, 0xb8, 0xc3, 0x9e, 0xa1, 0xe6, 0xfd, 0x76, 0x3d, 0x9d,
	0xce, 0xf2, 0xb3, 0xf8, 0xfe, 0x18, 0x88, 0x2b, 0x10, 0x65, 0xeb, 0x1c, 0x9a, 0xf0, 0x46, 0xab,
	0xb9, 0xae, 0x75, 0xd0, 0xe8, 0xf3, 0x73, 0x3e, 0xc2, 0xff, 0x28, 0xe2, 0x3b, 0xb8, 0xe0, 0x83,
	0x1f, 0x66, 0x7f, 0xc2, 0xd9, 0x8f, 0x78, 0xf1, 0x3d, 0x3c, 0x63, 0x2e, 0x9e, 0xf1, 0xe6, 0xa1,
	0xd5, 0x61, 0x93, 0x5f, 0x70, 0xf2, 0x63, 0x41, 0x7c, 0x0b, 0xe7, 0xa5, 0x5a, 0xe9, 0xa0, 0x6a,
	0x89, 0x1e, 0xdd, 0x1a, 0xf3, 0x67, 0x9c, 0xfa, 0x01, 0x4b, 0x0e, 0xb4, 0x59, 0xa3, 0x0f, 0x0d,
	0x9a, 0xc0, 0x3d, 0xc4, 0x5c, 0x44, 0x07, 0x1f, 0xf2, 0x85, 0x82, 0xec, 0xd6, 0x54, 0xf8, 0xc7,
	0x93, 0xdf, 0xff, 0x0b, 0x00, 0xbf, 0x1d, 0x18, 0x3e, 0x4f, 0x27, 0xe9, 0xe5, 0xe8, 0xe5, 0x45,
	0x1c, 0x75, 0x57, 0xbb, 0x49, 0x22, 0x0f, 0x72, 0x8a, 0x1f, 0x60, 0x70, 0x73, 0xf7, 0xfa, 0xa9,
	0x1f, 0x28, 0xfe, 0xea, 0x41, 0xff, 0x97, 0x37, 0xda, 0x20, 0xa9, 0x34, 0xca, 0xba, 0xe7, 0xc0,
	0x31, 0x71, 0x76, 0x85, 0x86, 0x57, 0x24, 0x92, 0x63, 0xe2, 0x16, 0xfa, 0xdd, 0x82, 0x6f, 0x7e,
	0x22, 0x39, 0xa6, 0x97, 0x54, 0xdb, 0xf7, 0x7c, 0xd9, 0x13, 0x49, 0x21, 0x4f, 0xd7, 0xda, 0xfa,
	0x38, 0x06, 0x13, 0x19, 0x01, 0x8d, 0xa1, 0xb5, 0xad, 0xdb, 0x06, 0xbb, 0x5b, 0xdd, 0x21, 0xe2,
	0x55, 0xc3, 0xc3, 0x78, 0xc0, 0xe9, 0x1d, 0x2a, 0xe6, 0x30, 0x66, 0x73, 0x12, 0x1f, 0x5a, 0xf4,
	0x81, 0xc7, 0xd8, 0xa6, 0x99, 0xdb, 0xba, 0x3b, 0x55, 0x87, 0x0e, 0x46, 0x61, 0x72, 0x34, 0x0a,
	0x0b, 0xe8, 0x2f, 0x69, 0x3d, 0x9b, 0x1d, 0xbd, 0x1c, 0x77, 0x95, 0x8b, 0x7b, 0x46, 0xa9, 0xf8,
	0xbb, 0x07, 0xc3, 0x6b, 0xbd, 0xd6, 0x15, 0x9a, 0xea, 0xa3, 0x3f, 0xb0, 0x2d, 0x5a, 0x7a, 0x5c,
	0xb4, 0x52, 0xf9, 0x45, 0x57, 0x0d, 0x8e, 0xa9, 0x1c, 0x2b, 0xa7, 0xcb, 0x5d, 0x39, 0x18, 0xec,
	0xff, 0x82, 0x4e, 0xbb, 0x22, 0xf1, 0x5f, 0x90, 0x80, 0x13, 0xb7, 0x1d, 0xb7, 0x89, 0xe4, 0x78,
	0x7e, 0xca, 0xc6, 0x7f, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x24, 0x4f, 0x35, 0x72, 0xec, 0x06,
	0x00, 0x00,
}
