// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: realtime.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Realtime_SubscribeRealtimeEvents_FullMethodName = "/pb.Realtime/SubscribeRealtimeEvents"
)

// RealtimeClient is the client API for Realtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Realtime is deliberately separate from the legacy Api service so its
// server-streaming lifecycle and generated stubs can evolve independently.
type RealtimeClient interface {
	SubscribeRealtimeEvents(ctx context.Context, in *SubscribeRealtimeEventsRequest, opts ...grpc.CallOption) (Realtime_SubscribeRealtimeEventsClient, error)
}

type realtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeClient(cc grpc.ClientConnInterface) RealtimeClient {
	return &realtimeClient{cc}
}

func (c *realtimeClient) SubscribeRealtimeEvents(ctx context.Context, in *SubscribeRealtimeEventsRequest, opts ...grpc.CallOption) (Realtime_SubscribeRealtimeEventsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Realtime_ServiceDesc.Streams[0], Realtime_SubscribeRealtimeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &realtimeSubscribeRealtimeEventsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Realtime_SubscribeRealtimeEventsClient interface {
	Recv() (*RealtimeEvent, error)
	grpc.ClientStream
}

type realtimeSubscribeRealtimeEventsClient struct {
	grpc.ClientStream
}

func (x *realtimeSubscribeRealtimeEventsClient) Recv() (*RealtimeEvent, error) {
	m := new(RealtimeEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RealtimeServer is the server API for Realtime service.
// All implementations must embed UnimplementedRealtimeServer
// for forward compatibility
//
// Realtime is deliberately separate from the legacy Api service so its
// server-streaming lifecycle and generated stubs can evolve independently.
type RealtimeServer interface {
	SubscribeRealtimeEvents(*SubscribeRealtimeEventsRequest, Realtime_SubscribeRealtimeEventsServer) error
	mustEmbedUnimplementedRealtimeServer()
}

// UnimplementedRealtimeServer must be embedded to have forward compatible implementations.
type UnimplementedRealtimeServer struct {
}

func (UnimplementedRealtimeServer) SubscribeRealtimeEvents(*SubscribeRealtimeEventsRequest, Realtime_SubscribeRealtimeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRealtimeEvents not implemented")
}
func (UnimplementedRealtimeServer) mustEmbedUnimplementedRealtimeServer() {}

// UnsafeRealtimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeServer will
// result in compilation errors.
type UnsafeRealtimeServer interface {
	mustEmbedUnimplementedRealtimeServer()
}

func RegisterRealtimeServer(s grpc.ServiceRegistrar, srv RealtimeServer) {
	s.RegisterService(&Realtime_ServiceDesc, srv)
}

func _Realtime_SubscribeRealtimeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRealtimeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeServer).SubscribeRealtimeEvents(m, &realtimeSubscribeRealtimeEventsServer{ServerStream: stream})
}

type Realtime_SubscribeRealtimeEventsServer interface {
	Send(*RealtimeEvent) error
	grpc.ServerStream
}

type realtimeSubscribeRealtimeEventsServer struct {
	grpc.ServerStream
}

func (x *realtimeSubscribeRealtimeEventsServer) Send(m *RealtimeEvent) error {
	return x.ServerStream.SendMsg(m)
}

// Realtime_ServiceDesc is the grpc.ServiceDesc for Realtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Realtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Realtime",
	HandlerType: (*RealtimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRealtimeEvents",
			Handler:       _Realtime_SubscribeRealtimeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "realtime.proto",
}
