// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stock struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{0}
}

func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (m *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(m, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Stock) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Stock) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StockRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bars                 int32    `protobuf:"varint,4,opt,name=bars,proto3" json:"bars,omitempty"`
	Match                string   `protobuf:"bytes,5,opt,name=match,proto3" json:"match,omitempty"`
	DataType             string   `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockRequest) Reset()         { *m = StockRequest{} }
func (m *StockRequest) String() string { return proto.CompactTextString(m) }
func (*StockRequest) ProtoMessage()    {}
func (*StockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{1}
}

func (m *StockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockRequest.Unmarshal(m, b)
}
func (m *StockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockRequest.Marshal(b, m, deterministic)
}
func (m *StockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockRequest.Merge(m, src)
}
func (m *StockRequest) XXX_Size() int {
	return xxx_messageInfo_StockRequest.Size(m)
}
func (m *StockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockRequest proto.InternalMessageInfo

func (m *StockRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *StockRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *StockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StockRequest) GetBars() int32 {
	if m != nil {
		return m.Bars
	}
	return 0
}

func (m *StockRequest) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *StockRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

type StockList struct {
	Stocks               []*Stock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockList) Reset()         { *m = StockList{} }
func (m *StockList) String() string { return proto.CompactTextString(m) }
func (*StockList) ProtoMessage()    {}
func (*StockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{2}
}

func (m *StockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockList.Unmarshal(m, b)
}
func (m *StockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockList.Marshal(b, m, deterministic)
}
func (m *StockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockList.Merge(m, src)
}
func (m *StockList) XXX_Size() int {
	return xxx_messageInfo_StockList.Size(m)
}
func (m *StockList) XXX_DiscardUnknown() {
	xxx_messageInfo_StockList.DiscardUnknown(m)
}

var xxx_messageInfo_StockList proto.InternalMessageInfo

func (m *StockList) GetStocks() []*Stock {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type ArchiveSummary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	DateStart            int32    `protobuf:"varint,3,opt,name=date_start,json=dateStart,proto3" json:"date_start,omitempty"`
	DateEnd              int32    `protobuf:"varint,4,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	ElapsedTime          int32    `protobuf:"varint,5,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveSummary) Reset()         { *m = ArchiveSummary{} }
func (m *ArchiveSummary) String() string { return proto.CompactTextString(m) }
func (*ArchiveSummary) ProtoMessage()    {}
func (*ArchiveSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{3}
}

func (m *ArchiveSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveSummary.Unmarshal(m, b)
}
func (m *ArchiveSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveSummary.Marshal(b, m, deterministic)
}
func (m *ArchiveSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveSummary.Merge(m, src)
}
func (m *ArchiveSummary) XXX_Size() int {
	return xxx_messageInfo_ArchiveSummary.Size(m)
}
func (m *ArchiveSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveSummary proto.InternalMessageInfo

func (m *ArchiveSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ArchiveSummary) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ArchiveSummary) GetDateStart() int32 {
	if m != nil {
		return m.DateStart
	}
	return 0
}

func (m *ArchiveSummary) GetDateEnd() int32 {
	if m != nil {
		return m.DateEnd
	}
	return 0
}

func (m *ArchiveSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

type StockInfo struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PreClose             float32  `protobuf:"fixed32,5,opt,name=pre_close,json=preClose,proto3" json:"pre_close,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ListDate             int32    `protobuf:"varint,8,opt,name=list_date,json=listDate,proto3" json:"list_date,omitempty"`
	DelistDate           int32    `protobuf:"varint,9,opt,name=delist_date,json=delistDate,proto3" json:"delist_date,omitempty"`
	LastTradeDate        int32    `protobuf:"varint,10,opt,name=last_trade_date,json=lastTradeDate,proto3" json:"last_trade_date,omitempty"`
	CircuShare           int64    `protobuf:"varint,11,opt,name=circu_share,json=circuShare,proto3" json:"circu_share,omitempty"`
	TotalShare           int64    `protobuf:"varint,12,opt,name=total_share,json=totalShare,proto3" json:"total_share,omitempty"`
	Industry             string   `protobuf:"bytes,13,opt,name=industry,proto3" json:"industry,omitempty"`
	Block                string   `protobuf:"bytes,14,opt,name=block,proto3" json:"block,omitempty"`
	SwL1                 string   `protobuf:"bytes,15,opt,name=sw_l1,json=swL1,proto3" json:"sw_l1,omitempty"`
	SwL2                 string   `protobuf:"bytes,16,opt,name=sw_l2,json=swL2,proto3" json:"sw_l2,omitempty"`
	SwL3                 string   `protobuf:"bytes,17,opt,name=sw_l3,json=swL3,proto3" json:"sw_l3,omitempty"`
	Concepts             []string `protobuf:"bytes,18,rep,name=concepts,proto3" json:"concepts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockInfo) Reset()         { *m = StockInfo{} }
func (m *StockInfo) String() string { return proto.CompactTextString(m) }
func (*StockInfo) ProtoMessage()    {}
func (*StockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{4}
}

func (m *StockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockInfo.Unmarshal(m, b)
}
func (m *StockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockInfo.Marshal(b, m, deterministic)
}
func (m *StockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockInfo.Merge(m, src)
}
func (m *StockInfo) XXX_Size() int {
	return xxx_messageInfo_StockInfo.Size(m)
}
func (m *StockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StockInfo proto.InternalMessageInfo

func (m *StockInfo) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *StockInfo) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *StockInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StockInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *StockInfo) GetPreClose() float32 {
	if m != nil {
		return m.PreClose
	}
	return 0
}

func (m *StockInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StockInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StockInfo) GetListDate() int32 {
	if m != nil {
		return m.ListDate
	}
	return 0
}

func (m *StockInfo) GetDelistDate() int32 {
	if m != nil {
		return m.DelistDate
	}
	return 0
}

func (m *StockInfo) GetLastTradeDate() int32 {
	if m != nil {
		return m.LastTradeDate
	}
	return 0
}

func (m *StockInfo) GetCircuShare() int64 {
	if m != nil {
		return m.CircuShare
	}
	return 0
}

func (m *StockInfo) GetTotalShare() int64 {
	if m != nil {
		return m.TotalShare
	}
	return 0
}

func (m *StockInfo) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *StockInfo) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *StockInfo) GetSwL1() string {
	if m != nil {
		return m.SwL1
	}
	return ""
}

func (m *StockInfo) GetSwL2() string {
	if m != nil {
		return m.SwL2
	}
	return ""
}

func (m *StockInfo) GetSwL3() string {
	if m != nil {
		return m.SwL3
	}
	return ""
}

func (m *StockInfo) GetConcepts() []string {
	if m != nil {
		return m.Concepts
	}
	return nil
}

// Form 10-K 年报?
type StockF10 struct {
	EPS                  int32    `protobuf:"varint,1,opt,name=EPS,proto3" json:"EPS,omitempty"`
	TotalAssets          int64    `protobuf:"varint,2,opt,name=totalAssets,proto3" json:"totalAssets,omitempty"`
	FlowProperty         int64    `protobuf:"varint,3,opt,name=flowProperty,proto3" json:"flowProperty,omitempty"`
	NetWorth             int32    `protobuf:"varint,4,opt,name=netWorth,proto3" json:"netWorth,omitempty"`
	MainIncoming         int64    `protobuf:"varint,5,opt,name=mainIncoming,proto3" json:"mainIncoming,omitempty"`
	MainProfit           int64    `protobuf:"varint,6,opt,name=mainProfit,proto3" json:"mainProfit,omitempty"`
	TotalProfit          int64    `protobuf:"varint,7,opt,name=totalProfit,proto3" json:"totalProfit,omitempty"`
	NetProfit            int64    `protobuf:"varint,8,opt,name=netProfit,proto3" json:"netProfit,omitempty"`
	ShareHolders         int32    `protobuf:"varint,9,opt,name=shareHolders,proto3" json:"shareHolders,omitempty"`
	ReportDate           int32    `protobuf:"varint,10,opt,name=reportDate,proto3" json:"reportDate,omitempty"`
	LiquidRatio          int32    `protobuf:"varint,11,opt,name=liquidRatio,proto3" json:"liquidRatio,omitempty"`
	QuickRatio           int32    `protobuf:"varint,12,opt,name=quickRatio,proto3" json:"quickRatio,omitempty"`
	UDPPS                int32    `protobuf:"varint,13,opt,name=UDPPS,proto3" json:"UDPPS,omitempty"`
	CurrentLiabilities   int64    `protobuf:"varint,14,opt,name=currentLiabilities,proto3" json:"currentLiabilities,omitempty"`
	TotalLiabilities     int64    `protobuf:"varint,15,opt,name=totalLiabilities,proto3" json:"totalLiabilities,omitempty"`
	TotalHolderEquity    int64    `protobuf:"varint,16,opt,name=totalHolderEquity,proto3" json:"totalHolderEquity,omitempty"`
	CapitalReserve       int64    `protobuf:"varint,17,opt,name=capitalReserve,proto3" json:"capitalReserve,omitempty"`
	InvestmentIncome     int64    `protobuf:"varint,18,opt,name=investmentIncome,proto3" json:"investmentIncome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockF10) Reset()         { *m = StockF10{} }
func (m *StockF10) String() string { return proto.CompactTextString(m) }
func (*StockF10) ProtoMessage()    {}
func (*StockF10) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{5}
}

func (m *StockF10) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockF10.Unmarshal(m, b)
}
func (m *StockF10) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockF10.Marshal(b, m, deterministic)
}
func (m *StockF10) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockF10.Merge(m, src)
}
func (m *StockF10) XXX_Size() int {
	return xxx_messageInfo_StockF10.Size(m)
}
func (m *StockF10) XXX_DiscardUnknown() {
	xxx_messageInfo_StockF10.DiscardUnknown(m)
}

var xxx_messageInfo_StockF10 proto.InternalMessageInfo

func (m *StockF10) GetEPS() int32 {
	if m != nil {
		return m.EPS
	}
	return 0
}

func (m *StockF10) GetTotalAssets() int64 {
	if m != nil {
		return m.TotalAssets
	}
	return 0
}

func (m *StockF10) GetFlowProperty() int64 {
	if m != nil {
		return m.FlowProperty
	}
	return 0
}

func (m *StockF10) GetNetWorth() int32 {
	if m != nil {
		return m.NetWorth
	}
	return 0
}

func (m *StockF10) GetMainIncoming() int64 {
	if m != nil {
		return m.MainIncoming
	}
	return 0
}

func (m *StockF10) GetMainProfit() int64 {
	if m != nil {
		return m.MainProfit
	}
	return 0
}

func (m *StockF10) GetTotalProfit() int64 {
	if m != nil {
		return m.TotalProfit
	}
	return 0
}

func (m *StockF10) GetNetProfit() int64 {
	if m != nil {
		return m.NetProfit
	}
	return 0
}

func (m *StockF10) GetShareHolders() int32 {
	if m != nil {
		return m.ShareHolders
	}
	return 0
}

func (m *StockF10) GetReportDate() int32 {
	if m != nil {
		return m.ReportDate
	}
	return 0
}

func (m *StockF10) GetLiquidRatio() int32 {
	if m != nil {
		return m.LiquidRatio
	}
	return 0
}

func (m *StockF10) GetQuickRatio() int32 {
	if m != nil {
		return m.QuickRatio
	}
	return 0
}

func (m *StockF10) GetUDPPS() int32 {
	if m != nil {
		return m.UDPPS
	}
	return 0
}

func (m *StockF10) GetCurrentLiabilities() int64 {
	if m != nil {
		return m.CurrentLiabilities
	}
	return 0
}

func (m *StockF10) GetTotalLiabilities() int64 {
	if m != nil {
		return m.TotalLiabilities
	}
	return 0
}

func (m *StockF10) GetTotalHolderEquity() int64 {
	if m != nil {
		return m.TotalHolderEquity
	}
	return 0
}

func (m *StockF10) GetCapitalReserve() int64 {
	if m != nil {
		return m.CapitalReserve
	}
	return 0
}

func (m *StockF10) GetInvestmentIncome() int64 {
	if m != nil {
		return m.InvestmentIncome
	}
	return 0
}

type IndexInfo struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StockInfos           []*StockInfo `protobuf:"bytes,3,rep,name=stockInfos,proto3" json:"stockInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexInfo) Reset()         { *m = IndexInfo{} }
func (m *IndexInfo) String() string { return proto.CompactTextString(m) }
func (*IndexInfo) ProtoMessage()    {}
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{6}
}

func (m *IndexInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexInfo.Unmarshal(m, b)
}
func (m *IndexInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexInfo.Marshal(b, m, deterministic)
}
func (m *IndexInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexInfo.Merge(m, src)
}
func (m *IndexInfo) XXX_Size() int {
	return xxx_messageInfo_IndexInfo.Size(m)
}
func (m *IndexInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IndexInfo proto.InternalMessageInfo

func (m *IndexInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexInfo) GetStockInfos() []*StockInfo {
	if m != nil {
		return m.StockInfos
	}
	return nil
}

type ETFInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETFInfo) Reset()         { *m = ETFInfo{} }
func (m *ETFInfo) String() string { return proto.CompactTextString(m) }
func (*ETFInfo) ProtoMessage()    {}
func (*ETFInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{7}
}

func (m *ETFInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETFInfo.Unmarshal(m, b)
}
func (m *ETFInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETFInfo.Marshal(b, m, deterministic)
}
func (m *ETFInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETFInfo.Merge(m, src)
}
func (m *ETFInfo) XXX_Size() int {
	return xxx_messageInfo_ETFInfo.Size(m)
}
func (m *ETFInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ETFInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ETFInfo proto.InternalMessageInfo

func (m *ETFInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ETFInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// K线
type KLine struct {
	Date                 int32    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Open                 float32  `protobuf:"fixed32,2,opt,name=open,proto3" json:"open,omitempty"`
	High                 float32  `protobuf:"fixed32,3,opt,name=high,proto3" json:"high,omitempty"`
	Low                  float32  `protobuf:"fixed32,4,opt,name=low,proto3" json:"low,omitempty"`
	Close                float32  `protobuf:"fixed32,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume               int64    `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount               float32  `protobuf:"fixed32,7,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KLine) Reset()         { *m = KLine{} }
func (m *KLine) String() string { return proto.CompactTextString(m) }
func (*KLine) ProtoMessage()    {}
func (*KLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{8}
}

func (m *KLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KLine.Unmarshal(m, b)
}
func (m *KLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KLine.Marshal(b, m, deterministic)
}
func (m *KLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KLine.Merge(m, src)
}
func (m *KLine) XXX_Size() int {
	return xxx_messageInfo_KLine.Size(m)
}
func (m *KLine) XXX_DiscardUnknown() {
	xxx_messageInfo_KLine.DiscardUnknown(m)
}

var xxx_messageInfo_KLine proto.InternalMessageInfo

func (m *KLine) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *KLine) GetOpen() float32 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *KLine) GetHigh() float32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *KLine) GetLow() float32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *KLine) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *KLine) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *KLine) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type KLineRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	KLine                *KLine   `protobuf:"bytes,3,opt,name=KLine,proto3" json:"KLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KLineRequest) Reset()         { *m = KLineRequest{} }
func (m *KLineRequest) String() string { return proto.CompactTextString(m) }
func (*KLineRequest) ProtoMessage()    {}
func (*KLineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{9}
}

func (m *KLineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KLineRequest.Unmarshal(m, b)
}
func (m *KLineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KLineRequest.Marshal(b, m, deterministic)
}
func (m *KLineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KLineRequest.Merge(m, src)
}
func (m *KLineRequest) XXX_Size() int {
	return xxx_messageInfo_KLineRequest.Size(m)
}
func (m *KLineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KLineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KLineRequest proto.InternalMessageInfo

func (m *KLineRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *KLineRequest) GetKLine() *KLine {
	if m != nil {
		return m.KLine
	}
	return nil
}

type KLineResponse struct {
	KLines               []*KLine `protobuf:"bytes,1,rep,name=KLines,proto3" json:"KLines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KLineResponse) Reset()         { *m = KLineResponse{} }
func (m *KLineResponse) String() string { return proto.CompactTextString(m) }
func (*KLineResponse) ProtoMessage()    {}
func (*KLineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{10}
}

func (m *KLineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KLineResponse.Unmarshal(m, b)
}
func (m *KLineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KLineResponse.Marshal(b, m, deterministic)
}
func (m *KLineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KLineResponse.Merge(m, src)
}
func (m *KLineResponse) XXX_Size() int {
	return xxx_messageInfo_KLineResponse.Size(m)
}
func (m *KLineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KLineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KLineResponse proto.InternalMessageInfo

func (m *KLineResponse) GetKLines() []*KLine {
	if m != nil {
		return m.KLines
	}
	return nil
}

// 除权除息
// 除权（XR）：exclude right
// 除息（XD）：exclude dividend
type XRXD struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ExDate               int32    `protobuf:"varint,2,opt,name=ex_date,json=exDate,proto3" json:"ex_date,omitempty"`
	Dividend             float32  `protobuf:"fixed32,3,opt,name=dividend,proto3" json:"dividend,omitempty"`
	PurchasePrice        float32  `protobuf:"fixed32,4,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	Split                float32  `protobuf:"fixed32,5,opt,name=split,proto3" json:"split,omitempty"`
	Purchase             float32  `protobuf:"fixed32,6,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XRXD) Reset()         { *m = XRXD{} }
func (m *XRXD) String() string { return proto.CompactTextString(m) }
func (*XRXD) ProtoMessage()    {}
func (*XRXD) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{11}
}

func (m *XRXD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XRXD.Unmarshal(m, b)
}
func (m *XRXD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XRXD.Marshal(b, m, deterministic)
}
func (m *XRXD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XRXD.Merge(m, src)
}
func (m *XRXD) XXX_Size() int {
	return xxx_messageInfo_XRXD.Size(m)
}
func (m *XRXD) XXX_DiscardUnknown() {
	xxx_messageInfo_XRXD.DiscardUnknown(m)
}

var xxx_messageInfo_XRXD proto.InternalMessageInfo

func (m *XRXD) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *XRXD) GetExDate() int32 {
	if m != nil {
		return m.ExDate
	}
	return 0
}

func (m *XRXD) GetDividend() float32 {
	if m != nil {
		return m.Dividend
	}
	return 0
}

func (m *XRXD) GetPurchasePrice() float32 {
	if m != nil {
		return m.PurchasePrice
	}
	return 0
}

func (m *XRXD) GetSplit() float32 {
	if m != nil {
		return m.Split
	}
	return 0
}

func (m *XRXD) GetPurchase() float32 {
	if m != nil {
		return m.Purchase
	}
	return 0
}

type XRXDResponse struct {
	XRXDS                []*XRXD  `protobuf:"bytes,1,rep,name=XRXDS,proto3" json:"XRXDS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XRXDResponse) Reset()         { *m = XRXDResponse{} }
func (m *XRXDResponse) String() string { return proto.CompactTextString(m) }
func (*XRXDResponse) ProtoMessage()    {}
func (*XRXDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{12}
}

func (m *XRXDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XRXDResponse.Unmarshal(m, b)
}
func (m *XRXDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XRXDResponse.Marshal(b, m, deterministic)
}
func (m *XRXDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XRXDResponse.Merge(m, src)
}
func (m *XRXDResponse) XXX_Size() int {
	return xxx_messageInfo_XRXDResponse.Size(m)
}
func (m *XRXDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_XRXDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_XRXDResponse proto.InternalMessageInfo

func (m *XRXDResponse) GetXRXDS() []*XRXD {
	if m != nil {
		return m.XRXDS
	}
	return nil
}

type Fundamental struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rawdata              []byte   `protobuf:"bytes,2,opt,name=rawdata,proto3" json:"rawdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fundamental) Reset()         { *m = Fundamental{} }
func (m *Fundamental) String() string { return proto.CompactTextString(m) }
func (*Fundamental) ProtoMessage()    {}
func (*Fundamental) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{13}
}

func (m *Fundamental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fundamental.Unmarshal(m, b)
}
func (m *Fundamental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fundamental.Marshal(b, m, deterministic)
}
func (m *Fundamental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fundamental.Merge(m, src)
}
func (m *Fundamental) XXX_Size() int {
	return xxx_messageInfo_Fundamental.Size(m)
}
func (m *Fundamental) XXX_DiscardUnknown() {
	xxx_messageInfo_Fundamental.DiscardUnknown(m)
}

var xxx_messageInfo_Fundamental proto.InternalMessageInfo

func (m *Fundamental) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Fundamental) GetRawdata() []byte {
	if m != nil {
		return m.Rawdata
	}
	return nil
}

type Rawdata struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	DataType             string   `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rawdata) Reset()         { *m = Rawdata{} }
func (m *Rawdata) String() string { return proto.CompactTextString(m) }
func (*Rawdata) ProtoMessage()    {}
func (*Rawdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{14}
}

func (m *Rawdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rawdata.Unmarshal(m, b)
}
func (m *Rawdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rawdata.Marshal(b, m, deterministic)
}
func (m *Rawdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rawdata.Merge(m, src)
}
func (m *Rawdata) XXX_Size() int {
	return xxx_messageInfo_Rawdata.Size(m)
}
func (m *Rawdata) XXX_DiscardUnknown() {
	xxx_messageInfo_Rawdata.DiscardUnknown(m)
}

var xxx_messageInfo_Rawdata proto.InternalMessageInfo

func (m *Rawdata) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Rawdata) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Rawdata) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Report struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{15}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Report) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Report) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Report) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Stock)(nil), "pb.Stock")
	proto.RegisterType((*StockRequest)(nil), "pb.StockRequest")
	proto.RegisterType((*StockList)(nil), "pb.StockList")
	proto.RegisterType((*ArchiveSummary)(nil), "pb.ArchiveSummary")
	proto.RegisterType((*StockInfo)(nil), "pb.StockInfo")
	proto.RegisterType((*StockF10)(nil), "pb.StockF10")
	proto.RegisterType((*IndexInfo)(nil), "pb.IndexInfo")
	proto.RegisterType((*ETFInfo)(nil), "pb.ETFInfo")
	proto.RegisterType((*KLine)(nil), "pb.KLine")
	proto.RegisterType((*KLineRequest)(nil), "pb.KLineRequest")
	proto.RegisterType((*KLineResponse)(nil), "pb.KLineResponse")
	proto.RegisterType((*XRXD)(nil), "pb.XRXD")
	proto.RegisterType((*XRXDResponse)(nil), "pb.XRXDResponse")
	proto.RegisterType((*Fundamental)(nil), "pb.Fundamental")
	proto.RegisterType((*Rawdata)(nil), "pb.Rawdata")
	proto.RegisterType((*Report)(nil), "pb.Report")
}

func init() { proto.RegisterFile("stock.proto", fileDescriptor_c87a7814fbd674bd) }

var fileDescriptor_c87a7814fbd674bd = []byte{
	// 1100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xef, 0x6e, 0xdc, 0x36,
	0x0c, 0xc0, 0x71, 0xe7, 0xf8, 0xfe, 0x30, 0x97, 0xb4, 0xd5, 0xfe, 0x79, 0xed, 0xd6, 0xa6, 0x06,
	0x56, 0x04, 0xc3, 0x1a, 0xac, 0xe9, 0x03, 0x0c, 0xc5, 0x9a, 0x6e, 0x41, 0x83, 0x21, 0xd0, 0x65,
	0x58, 0x3f, 0xcd, 0xd0, 0xd9, 0x4a, 0x4f, 0x8d, 0x6d, 0x39, 0x92, 0x9c, 0xf4, 0x9e, 0x63, 0x9f,
	0x86, 0xbd, 0xc2, 0x9e, 0x6c, 0xcf, 0xb0, 0x0f, 0x03, 0x29, 0xf9, 0xea, 0xa4, 0xcb, 0xb0, 0x0f,
	0xfd, 0x26, 0xfe, 0x48, 0x53, 0x24, 0xc5, 0x23, 0x0f, 0x36, 0xad, 0xd3, 0xf9, 0xd9, 0x5e, 0x63,
	0xb4, 0xd3, 0x6c, 0xd8, 0x2c, 0xd2, 0x97, 0x10, 0xcf, 0x11, 0xb1, 0x4f, 0x61, 0x54, 0x09, 0x73,
	0x26, 0x5d, 0x32, 0xd8, 0x19, 0xec, 0x4e, 0x79, 0x90, 0x90, 0xdb, 0x55, 0xb5, 0xd0, 0x65, 0x32,
	0xf4, 0xdc, 0x4b, 0x8c, 0xc1, 0x46, 0x2d, 0x2a, 0x99, 0x44, 0x44, 0xe9, 0x9c, 0xfe, 0x3e, 0x80,
	0x19, 0x79, 0xe3, 0xf2, 0xbc, 0x95, 0xd6, 0x7d, 0x08, 0xa7, 0xc8, 0x16, 0xc2, 0xd8, 0x64, 0x63,
	0x67, 0xb0, 0x1b, 0x73, 0x3a, 0xb3, 0x8f, 0x21, 0xae, 0x84, 0xcb, 0x97, 0x49, 0x4c, 0x86, 0x5e,
	0x60, 0xf7, 0x60, 0x5a, 0x08, 0x27, 0x32, 0xb7, 0x6a, 0x64, 0x32, 0x22, 0xcd, 0x04, 0xc1, 0xc9,
	0xaa, 0x91, 0xe9, 0x1e, 0x4c, 0x29, 0xb4, 0x23, 0x65, 0x1d, 0x7b, 0x08, 0x23, 0x2a, 0x84, 0x4d,
	0x06, 0x3b, 0xd1, 0xee, 0xe6, 0xfe, 0x74, 0xaf, 0x59, 0xec, 0xf9, 0xc8, 0x83, 0x22, 0xfd, 0x6d,
	0x00, 0xdb, 0xcf, 0x4c, 0xbe, 0x54, 0x17, 0x72, 0xde, 0x56, 0x95, 0x30, 0x2b, 0xb6, 0x0d, 0x43,
	0x55, 0x84, 0x4c, 0x86, 0xaa, 0xc0, 0x28, 0x72, 0xdd, 0xd6, 0x8e, 0x92, 0x88, 0xb9, 0x17, 0xd8,
	0x97, 0x00, 0x85, 0x70, 0x32, 0xb3, 0x4e, 0x18, 0x47, 0x99, 0xc4, 0x1c, 0xe3, 0x92, 0x73, 0x04,
	0xec, 0x73, 0x98, 0x90, 0x5a, 0xd6, 0x45, 0x48, 0x69, 0x8c, 0xf2, 0x41, 0x5d, 0xb0, 0x87, 0x30,
	0x93, 0xa5, 0x68, 0xac, 0x2c, 0x32, 0xa7, 0x2a, 0x49, 0xc9, 0xc5, 0x7c, 0x33, 0xb0, 0x13, 0x55,
	0xc9, 0xf4, 0xaf, 0x28, 0xa4, 0x71, 0x58, 0x9f, 0xea, 0x0f, 0x52, 0xde, 0x7b, 0x30, 0x3d, 0x6d,
	0xcb, 0x32, 0x23, 0xc5, 0x86, 0x2f, 0x1a, 0x82, 0x9f, 0x82, 0xb2, 0x31, 0x32, 0xcb, 0x4b, 0x6d,
	0x7d, 0x38, 0x43, 0x3e, 0x69, 0x8c, 0xfc, 0x1e, 0x65, 0xf4, 0xd6, 0xab, 0x34, 0x9d, 0xe9, 0x66,
	0x27, 0x5c, 0x6b, 0x93, 0x71, 0xb8, 0x99, 0x24, 0x74, 0x54, 0x2a, 0xeb, 0x32, 0x4c, 0x35, 0x99,
	0x50, 0x5e, 0x13, 0x04, 0xcf, 0x85, 0x93, 0xec, 0x01, 0x6c, 0x16, 0xf2, 0x9d, 0x7a, 0x4a, 0x6a,
	0xf0, 0x88, 0x0c, 0x1e, 0xc1, 0xad, 0x52, 0x58, 0x97, 0x39, 0x23, 0x0a, 0xe9, 0x8d, 0x80, 0x8c,
	0xb6, 0x10, 0x9f, 0x20, 0xed, 0x1c, 0xe5, 0xca, 0xe4, 0x6d, 0x66, 0x97, 0xc2, 0xc8, 0x64, 0x73,
	0x67, 0xb0, 0x1b, 0x71, 0x20, 0x34, 0x47, 0x82, 0x06, 0x4e, 0x3b, 0x51, 0x06, 0x83, 0x99, 0x37,
	0x20, 0xe4, 0x0d, 0xee, 0xc2, 0x44, 0xd5, 0x45, 0x6b, 0x9d, 0x59, 0x25, 0x5b, 0xbe, 0x18, 0x9d,
	0x8c, 0xcf, 0xbd, 0x28, 0x75, 0x7e, 0x96, 0x6c, 0xfb, 0xa6, 0x23, 0x81, 0x7d, 0x04, 0xb1, 0xbd,
	0xcc, 0xca, 0x27, 0xc9, 0x2d, 0x5f, 0x06, 0x7b, 0x79, 0xf4, 0xa4, 0x83, 0xfb, 0xc9, 0xed, 0x35,
	0xdc, 0xef, 0xe0, 0xd3, 0xe4, 0xce, 0x1a, 0x3e, 0xc5, 0x0b, 0x73, 0x5d, 0xe7, 0xb2, 0x71, 0x36,
	0x61, 0x3b, 0x11, 0x5e, 0xd8, 0xc9, 0xe9, 0xdf, 0x1b, 0x30, 0xa1, 0xc7, 0x7e, 0xf1, 0xe4, 0x5b,
	0x76, 0x1b, 0xa2, 0x83, 0xe3, 0x39, 0x3d, 0x74, 0xcc, 0xf1, 0xc8, 0x76, 0x42, 0x32, 0xcf, 0xac,
	0x95, 0xce, 0xd2, 0x53, 0x47, 0xbc, 0x8f, 0x58, 0x0a, 0xb3, 0xd3, 0x52, 0x5f, 0x1e, 0x1b, 0xdd,
	0x48, 0xe3, 0x56, 0xf4, 0xee, 0x11, 0xbf, 0xc2, 0x30, 0x80, 0x5a, 0xba, 0x5f, 0xb4, 0x71, 0xcb,
	0xd0, 0x8f, 0x6b, 0x19, 0xbf, 0xaf, 0x84, 0xaa, 0x0f, 0xeb, 0x5c, 0x57, 0xaa, 0x7e, 0x4d, 0x1d,
	0x10, 0xf1, 0x2b, 0x8c, 0xdd, 0x07, 0x40, 0xf9, 0xd8, 0xe8, 0x53, 0xe5, 0xa8, 0x17, 0x22, 0xde,
	0x23, 0xeb, 0x28, 0x83, 0xc1, 0xb8, 0x17, 0x65, 0xb0, 0xf8, 0x02, 0xa6, 0xb5, 0x74, 0x41, 0x3f,
	0x21, 0xfd, 0x3b, 0x80, 0x31, 0xd0, 0x63, 0xfd, 0xa8, 0xcb, 0x42, 0x1a, 0x1b, 0xba, 0xe3, 0x0a,
	0xc3, 0x18, 0x8c, 0x6c, 0xb4, 0xa1, 0x6e, 0x09, 0xad, 0xd1, 0x23, 0x18, 0x43, 0xa9, 0xce, 0x5b,
	0x55, 0x70, 0xe1, 0x94, 0xa6, 0xbe, 0x88, 0x79, 0x1f, 0xa1, 0x87, 0xf3, 0x56, 0xe5, 0x67, 0xde,
	0x60, 0xe6, 0x3d, 0xbc, 0x23, 0xf8, 0xf6, 0x3f, 0x3f, 0x3f, 0x3e, 0x9e, 0x53, 0x53, 0xc4, 0xdc,
	0x0b, 0x6c, 0x0f, 0x58, 0xde, 0x1a, 0x23, 0x6b, 0x77, 0xa4, 0xc4, 0x42, 0x95, 0xca, 0x29, 0x69,
	0xa9, 0x3d, 0x22, 0xfe, 0x2f, 0x1a, 0xf6, 0x35, 0xdc, 0xa6, 0xc4, 0xfb, 0xd6, 0xb7, 0xc8, 0xfa,
	0x3d, 0xce, 0xbe, 0x81, 0x3b, 0xc4, 0x7c, 0x8e, 0x07, 0xe7, 0xad, 0x72, 0x2b, 0x6a, 0xa7, 0x88,
	0xbf, 0xaf, 0x60, 0x8f, 0x60, 0x3b, 0x17, 0x8d, 0x72, 0xa2, 0xe4, 0xd2, 0x4a, 0x73, 0x21, 0xa9,
	0xc9, 0x22, 0x7e, 0x8d, 0x62, 0x04, 0xaa, 0xbe, 0x90, 0xd6, 0x55, 0xb2, 0x76, 0xf4, 0x86, 0x32,
	0x61, 0x3e, 0x82, 0xeb, 0x3c, 0xfd, 0x15, 0xa6, 0x87, 0x75, 0x21, 0xdf, 0xd2, 0xa8, 0xb9, 0x3e,
	0xfb, 0xba, 0x51, 0x32, 0xec, 0x8d, 0x92, 0xc7, 0x00, 0xb6, 0x9b, 0x4d, 0x36, 0x89, 0x68, 0xb2,
	0x6e, 0xad, 0x27, 0x2b, 0x52, 0xde, 0x33, 0x48, 0x1f, 0xc3, 0xf8, 0xe0, 0xe4, 0xc5, 0xff, 0xf5,
	0x9e, 0xfe, 0x31, 0x80, 0xf8, 0xe5, 0x91, 0xaa, 0x69, 0xf0, 0xd0, 0x0c, 0xf0, 0xbf, 0x05, 0x3a,
	0x23, 0xd3, 0x8d, 0xac, 0xe9, 0x8b, 0x21, 0xa7, 0x33, 0xb2, 0xa5, 0x7a, 0xbd, 0xa4, 0xb6, 0x1f,
	0x72, 0x3a, 0xe3, 0xcf, 0xa8, 0xd4, 0x97, 0xd4, 0xe9, 0x43, 0x8e, 0x47, 0x9a, 0xe2, 0xbd, 0xf9,
	0xe6, 0x05, 0x1c, 0x64, 0x17, 0xba, 0x6c, 0x2b, 0x19, 0x5a, 0x3a, 0x48, 0xc8, 0x45, 0x45, 0x43,
	0x7f, 0x4c, 0xe6, 0x41, 0x4a, 0x7f, 0x80, 0x19, 0x05, 0xd7, 0xdb, 0x7c, 0x61, 0x04, 0x0f, 0xae,
	0x8c, 0xe0, 0x07, 0x21, 0x09, 0x0a, 0x2a, 0x2c, 0x1e, 0xff, 0xa1, 0xe7, 0xe9, 0x3e, 0x6c, 0x05,
	0x47, 0xb6, 0xd1, 0xb5, 0x95, 0xb8, 0xab, 0x08, 0x5c, 0xd9, 0x55, 0xde, 0x24, 0x28, 0xd2, 0x3f,
	0x07, 0xb0, 0xf1, 0x8a, 0xbf, 0x7a, 0x7e, 0xe3, 0xad, 0x9f, 0xc1, 0x58, 0xbe, 0xf5, 0x83, 0xd3,
	0xef, 0xaa, 0x91, 0x7c, 0x4b, 0xbf, 0x8c, 0xbb, 0x30, 0x29, 0xd4, 0x85, 0x2a, 0x70, 0x1b, 0xf9,
	0x32, 0xad, 0x65, 0xf6, 0x15, 0x6c, 0x37, 0xad, 0xc9, 0x97, 0xc2, 0xca, 0xac, 0x31, 0x2a, 0x97,
	0xa1, 0x6a, 0x5b, 0x1d, 0x3d, 0x46, 0x88, 0xf5, 0xb3, 0x4d, 0xa9, 0x5c, 0x57, 0x3f, 0x12, 0xd0,
	0x71, 0x67, 0x46, 0x15, 0xc4, 0xc5, 0x11, 0xe4, 0x74, 0x0f, 0x66, 0x18, 0xed, 0x3a, 0xc3, 0xfb,
	0x10, 0xa3, 0x3c, 0x0f, 0x09, 0x4e, 0x30, 0x41, 0x32, 0xf0, 0x38, 0xfd, 0x0e, 0x36, 0x5f, 0xb4,
	0x75, 0x21, 0xb0, 0x37, 0x45, 0x79, 0x63, 0x92, 0x09, 0x8c, 0x8d, 0xb8, 0xc4, 0x85, 0x4f, 0x49,
	0xce, 0x78, 0x27, 0xa6, 0x1c, 0xc6, 0xdc, 0x1f, 0x6f, 0xfc, 0xf8, 0xbf, 0xfe, 0x3b, 0xd0, 0x5f,
	0x10, 0x5d, 0xac, 0x82, 0x5b, 0x3a, 0xa7, 0x19, 0x8c, 0x38, 0x4d, 0x98, 0x1b, 0x5d, 0x7e, 0x02,
	0xa3, 0x37, 0x7a, 0x91, 0xa9, 0x22, 0xb4, 0x71, 0xfc, 0x46, 0x2f, 0x0e, 0x8b, 0xf5, 0xda, 0x8c,
	0x7a, 0x6b, 0xb3, 0xbb, 0xc0, 0xef, 0x5f, 0x3a, 0x2f, 0x46, 0xf4, 0x27, 0xed, 0xe9, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc4, 0xa5, 0x6f, 0x1a, 0xb3, 0x09, 0x00, 0x00,
}
